### ISSUE TITLE
Create insert-token and remove-token

### ISSUE THREAD

**Issue by GPPassos** [own-pt/cl-conllu#10]
Functions for inserting and removing tokens from sentences are needed. It's necessary to not only to insert [remove] corresponding rows, but also re-enumerate ids (and references, at the head field) in other rows.

**Comment by GPPassos** [comment]
TODO list:
- [x] Make it "smart" with multitokens (if I remove a token from a multitoken, perhaps I should remove this associated multitoken, shouldn't I?)
  - Done in 8fb724f: safe - if I try to remove it, it won't let me (until I remove the multitoken)
  - Perhaps add an option to force-remove, removing the multitoken too?

Decisions made (until now, can be reviewed anytime!):
- `push-token` "pushes" every token after the inserted one (increases ID by 1, fixing HEAD values)
- `pop-token` "pulls" every token after the removed one (reduces ID by 1, fixing HEAD values);
if HEAD value was from token removed, it becomes "_"
- both functions change `sentence` object (instead of returning a modified copy)
- `pop-token` returns removed token, `push-token` returns sentence

**Comment by arademaker** [comment]
@GPPassos better make the functions 'save', never modify the arguments.

**Comment by GPPassos** [comment]
Updated by 8fb724f, and it works. We can close this issue or leave it be until making them functional or adding an option to force-remove.

**Comment by arademaker** [comment]
done via 0de6034
