### ISSUE TITLE
Wrong metadata format

### ISSUE THREAD

**Issue by fcbr** [own-pt/cl-conllu#12]
According to http://universaldependencies.org/format.html metadata needs to be separate between a `=` between key and value.

We need to:

1. support the new and old formats
2. write only the new

This way we can easily convert existing CONLL-U files.

**Comment by arademaker** [comment]
In http://universaldependencies.org/format.html the documentation about the metadata and comments:

> Lines starting with the # character and preceding a sentence are considered as carrying metadata relevant to the following sentence. These lines are an integral part of the format as they give the ability to embed metadata together with the sentences. Consequently, any tools compatible with the CoNLL-U format should carry these lines over into their output (unless specifically designed to process them in some way). The contents of the comments and metadata is basically unrestricted and will vary depending on the application, but from v2 every sentence must have a unique sentence id, formatted as in the examples below. In sentence ids, the slash character (“/”) is reserved for specialized downstream use and should be avoided in UD treebanks. Comments used to specify the unannotated sentence as a single string should also be formatted as below. Comment and metadata lines inside sentences (i.e., between the token lines) are disallowed.

We have two possibilities:

1. we will consider that ALL comment lines preceding a sentence carrying metadata in the format `KEY = VALUE`, or 
2. we will have both cases of comment lines with and without meta

Suggestions?

**Comment by arademaker** [comment]
close via b99d8c460b9e780cff363d31742513d82a4f4d53

**Comment by arademaker** [comment]
See also 8bc0476, improved validation , all sentence MUST have the `text` and `sent_id` metadata.
