### ISSUE TITLE
make read-conllu more robust

### ISSUE THREAD

**Issue by arademaker** [own-pt/cl-conllu#14]
We need better error handling and messages.

**Comment by arademaker** [comment]
This is also related with #6 , we need to make this library much more robust. The CL conditions and restarts are powerful exception handling tool in CL, we need to explore it:

http://www.gigamonkeys.com/book/beyond-exception-handling-conditions-and-restarts.html

**Comment by vcvpaiva** [comment]
minor rewrite: "robuster" doesn't exist, it has to be "more robust"

**Comment by arademaker** [comment]
In a7d497a I didn't solve the error handling properly. But we add more robustness in the parser accepting a minimal file with no pos tagging nor dependencies.

**Comment by arademaker** [comment]
Commit b6554cff7bb3ebef9d338cce495eb0ad71127170 introduced a funtion with a `(format ...)` and a conditional being used as error handler. This kind of approach does not make this system robust. 

@Kalysthos pode cuidar disso?

**Comment by arademaker** [comment]
We need much more work on the reader. Commit b067afb8d783bfc7021c466a8a1d05844bcc37da introduce proper error-classes, simplify the code and improve performance. But this issue is too generic. I will close it now and open more specific ones.
