### ISSUE TITLE
Projective sentences

### ISSUE THREAD

**Issue by GPPassos** [own-pt/cl-conllu#24]
To add a function that verifies if a dependency parse of a sentence is [projective](https://en.wikipedia.org/wiki/Discontinuity_(linguistics)#Dependency-based_projectivity) or not.

I've done already two commits about it: 79bcc35 and 7c6f700, but testing (and possibly improving the code) is still necessary.

**Comment by GPPassos** [comment]
I believe 4685214 implements it correctly, but I think it'd be useful to:
- [ ] do more testing (using, as I've done with one example, this [prove](https://github.com/fukamachi/prove) package)
- [ ] improve documentation
as it is, it documents the problem, but doesn't explain the implementation. As the algorithm isn't out-of-the-shelf, but I've though of it myself (and sketched a correctness proof), even if it's simple it'd be nice to have an explanation somewhere

**Comment by arademaker** [comment]
solved by #85
