### ISSUE TITLE
Functions for evaluating parsers

### ISSUE THREAD

**Issue by GPPassos** [own-pt/cl-conllu#25]
It's useful to have functions for evaluating parsers (UAS, LAS, precision, ecall, confusion matrix, etc), testing results of sentences against a golden dataset. I'll use them myself this week.

I'm starting the eval-functions branch in order to develop this and already did the first commit: 439d192.

**Comment by arademaker** [comment]
@GPPassos great, but it would be useful to always share the links and ideas of implementation before the actual implementation. Please make this issue the place for post these information.

**Comment by GPPassos** [comment]
Ok! For the moment I've made small fixes based on your comments on the commit 5c3bc35
(I forgot to reference the issue on the commit message...)

**Comment by arademaker** [comment]
@claudiafreitas disse:

Comentários:
essa verificação compara o tipo da relação, certo? è preciso comparar também as dependências - e , idealmente, a conjugação de dependência e tipo de relação, ja que as duas coisas andam juntas.

Pra ficar legal do lado dos linguistas, era bom também produzir uma saída "qualitativa", isto é, 
olhando a matriz de confusão, temos que em 16 casos, o sistema deveria ter classificado nsubj mas classificou obj. Para nós seria importante uma lista com as frases em que isso aconteceu, com a indicação da palavra com a análise equivocada, tipo:

Joana[NSUBJ>OBJ] comprou um bolo

**Comment by arademaker** [comment]
Importante pensarmos também como comparar anotações de diferentes anotadores (2 ou mais).
