### ISSUE TITLE
query language

### ISSUE THREAD

**Issue by arademaker** [own-pt/cl-conllu#3]
Given that we have already the classes sentence and tokens, can we make a query interface? 

- http://bionlp.utu.fi/searchexpressions-new.html
- http://lindat.mff.cuni.cz/services/pmltq/#!/treebank/ud_pt/help
- http://clarino.uib.no/iness/dep-query?query-has-run=true&session-id=241762092672273

Last link, query example:

```
#x:[pos="VERB" & word & lemma="ficar"] . #y:[pos="VERB" & word & lemma]
```

another alternative is to have a backend (ES, Solr, triple store) and a mapping from a expression lang to the backend query language.

http://wesearch.delph-in.net/deepbank/search.jsp

another option, convert to prolog and use any of CL implementations of PROLOG:

http://www.cliki.net/prolog

A query would be something like de expression below that could filter sentences from a list of sentences:

```
(lemma tk1 "fazer") and (pos tk1 VERB) and (pos tk2 VERB) and (aux tk1 tk2) 
```

**Comment by arademaker** [comment]
@claudiafreitas escreveu:

No [AC/DC](http://www.linguateca.pt/acesso/corpus.php?corpus=FLORESTA), é possível esse tipo de busca, que lida com variável:

```
"de" a:[pos="N.*"] "em" @[word=a.word] within s
```
Esta linguagem é bem parecida com a linguagem de http://clarino.uib.no/iness/page?page-id=INESS_Search e no rules.lisp temos algo iniciado nesta direção mas apenas para aplicar regras.

**Comment by claudiafreitas** [comment]
reparem que na expressão 

> "de" a:[pos="N.*"] "em" @[word=a.word] within s

não há qualquer informação de dependência-correlação, é uma expressão que recupera sequências lineares, tipo  "de mão em mão", "de tempos em tempos" etc (aliás, essa busca é uma ótima maneira de identificar mwes..).
Não é possível no ACDC, mesmo com a utilização de variáveis, lidar com coisas não lineares... Ou seja: quero buscar pelo objeto direto de um verbo. Em

> O presidente da empresa de cosméticos avaliou, apesar de todas as expectativas indicarem o contrário, o contrato como altamente positivo.

quero que "contrato" seja recuperado como objeto de "avaliar", e não "contrário" (que também é objeto, mas do verbo "indicar". ) é importante que a sintaxe de busca consiga implementar/recuperar esse tipo de coisa.

**Comment by arademaker** [comment]
XML based alternatives? 

http://ps.clul.ul.pt/index.php?action=corpussearch

o backend qual é? Não sei, pode ser algo como:

http://www.exist-db.org/exist/apps/homepage/index.html

**Comment by arademaker** [comment]
Commit 1c9efdc closes this issue. A new issue for optimize the query interface will be open.
