### ISSUE TITLE
Does not build today - argument mismatch

### ISSUE THREAD

**Issue by quicklisp** [own-pt/cl-conllu#38]
I get this:

    ; in: DEFUN DEEP-AUX
    ;     (CL-CONLLU::DEEP-AUX CL-CONLLU::CHILD CL-CONLLU:SENTENCE CL-CONLLU::FN-KEY)
    ; 
    ; caught WARNING:
    ;   The function was called with three arguments, but wants exactly two.

**Comment by arademaker** [comment]
Solved in d84b470
